name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y taskwarrior

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true

      - name: Run Makefile tasks
        run: |
          make deps
          make install_plugins
          make lint
          make test

